# Generated by Django 5.0.6 on 2024-09-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_user_followers_remove_user_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.TextField(blank=True),
        ),
    ]
