# Generated by Django 5.0.6 on 2024-09-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likePost',
            field=models.TextField(blank=True),
        ),
    ]
