# Generated by Django 5.0.6 on 2024-09-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likeCount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likePost',
        ),
        migrations.AddField(
            model_name='post',
            name='likedUser',
            field=models.TextField(blank=True),
        ),
    ]
