# Generated by Django 5.0.6 on 2024-09-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_rename_like_post_likecount_remove_user_likepost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likedUser',
            new_name='likeUser',
        ),
    ]
